### ISSUE TITLE
findmypi

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/UBpi#4]
@samlane-ma 

  Find My Pi stuff works really nicely - so congrats for working through the issues here.

Initial thoughts:

1. Installing nmap as part of a dependency of the config app is problematic in some countries.  I think its a great technique to use to find pi's but I would err on the side of caution - a button possibly needs to be in the FindMyPi mode that first displays a dialog warning users to check if nmap port-scanning is legal in their country before installing.
2. So the UDP server option is perhaps the first port-of-call here.  Perhaps on the remote tab have an option to 
a. start findmypiserver.py
b. enable an autostart file to run findmypiserver.py on logon.
3. if nmap is installed then there doesnt seem to be any point to autostart findmypiserver since that should be the default.  I dont find the speed really an issue on my home network.

**Comment by samlane-ma** [comment]
1. I can also investigate other methods that may be safer / less possible legal issues to update the arp table than nmap.  Additionally, this can probably also be changed to use /proc/net/arp instead of the arp command, to avoid net-tools dependency.
2. Will start working on this.  Additional benefit of the UDP server method is it can be expanded upon if ever desired (i.e. An "info" button could be added in the future, and the server could also respond with info like PI's cpu temp, uptime, etc...)
3. Easy enough, can be made to look for nmap and if not available, fallback to UDP method.

**Comment by samlane-ma** [comment]
Minor adjustments to start addressing some of these points - but certainly more work to do on them:
- If nmap and arp are installed, it will use this method automatically. If not, it defaults to the UDP server.
- Warning dialog is shown if nmap/arp is being used.  Currently it shows on startup if in nmap/arp mode.  This will eventually be moved to the function that installs nmap (or possibly also on first run also if nmap is already installed?)  If Cancel is clicked, it falls back to the UDP server method.
- The treeview now does not start updating until FindMyPiTreeView.start() is called.  This way, it is not scanning using nmap until AFTER the warning is displayed and OK is clicked (allows better control of the treeview, too)

**Comment by samlane-ma** [comment]
Other issues to address:
4. Refresh button in nmap mode - Currently clicking to refresh the list won't run nmap unless enough time has elapsed since last one.  Probably should force a full scan, as the primary reason for a manual refresh would likely be if a PI was added or removed recently and you don't want to wait for the scheduled check interval.  However, it also should not force this nmap scan if one was done very recently.
