### ISSUE TITLE
Add an override to launch ubpi mode

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/UBpi#7]
Thinking of this commit 377eb628488aa48e419c2a2663e6b081ce94e544

Would it be a good idea to  have some-sort of command  line interface to allow ubpi to be launched correctly if new pi variants are launched/found between ubuntu releases?

so for example 

    <app> --model CM4 --cpuinfo "Pi Compute Module 4"

could then make sure the app runs up in the mode we expect

or maybe

    <app> --force-pi-mode
    <app> --force-findip-mode

To override which interface is run ... for example maybe you could have a suite of Pi's - and maybe a user would want one to be finding the other Pi's on the network

and/or 

      <app> --get-cpu-info

To obtain the current cpuinfo.

Maybe other 'hard-coded' or deemed "get-info" type parameters could be useful?

**Comment by samlane-ma** [comment]
We are on the same page because I was considering the same thing.

At minimum, it can be changed to detect if it’s a pi, even if it can’t determine the exact model. 

Forcing models is a good idea, since certain models may needed to be treated different (i.e. a pi 4, 400, and CM4 are all Pi 4s in essence, but a CM4 should be treated like a Pi4, while a 400 runs at 1.8GHz instead of 1.5, so it needs to be treated different by the overclock module).  Forcing would allow control of how a new model is treated.

Also agree with being able to force which mode it starts up in.  Currently no easy way to run the findmypi on a pi.

Will start thinking on this.

**Comment by fossfreedom** [comment]
Double checking the current implementation - if you run ubpi with an unknown parameter / --help / "/?" then it should not run the app but instead display all available options e.g. python3 --help

This is to allow "discoverability" for command line users.

**Comment by samlane-ma** [comment]
Yes, still refinement needed but currently:

`python3 main.py -h`

```
usage: main.py [-h] [--force-findpi-mode] [--force-arm-mode] [--force-model {CM4,4,400}] [--model MODEL] [--cpuinfo CPUINFO]

optional arguments:
  -h, --help            show this help message and exit
  --force-findpi-mode   Start up in FindMyPi mode
  --force-arm-mode      Start in Config App mode
  --force-model {CM4,4,400}
  --model MODEL
  --cpuinfo CPUINFO
```

Obviously --force-model, --model, and --cpuinfo need descriptions.

Using --model without --cpuinfo gives a  message too (or vice versa):
```
usage: main.py [-h] [--force-findpi-mode] [--force-arm-mode] [--force-model {CM4,4,400}] [--model MODEL] [--cpuinfo CPUINFO]
main.py: error: number of --cpuinfo and --model arguments must match
```
Would also like to change it so Optional Arguments are printed on invalid parameter, instead of just the usage line:
```
usage: main.py [-h] [--force-findpi-mode] [--force-arm-mode] [--force-model {CM4,4,400}] [--model MODEL] [--cpuinfo CPUINFO]
main.py: error: unrecognized arguments: -u
```

**Comment by samlane-ma** [comment]
Added the final --get-model-info option, which will now return the Pi model and memory size
The --help parameter has a brief description of what the options do
