### ISSUE TITLE
Minecraft Java is unplayable

### ISSUE THREAD

**Issue by ghost** [UbuntuBudgie/UBpi#9]
I tried Minecraft 1.16.5 with optifine and it runs so bad its unplayable
0-8fps with average of 1-3fps is very bad
Minecraft is unplayable
Please fix this with in future releases aka 21.10
Minecraft should not run that bad on it
I have seen better on beta's
as some of the beta budgie builds, minecraft was actually playable with average above 5fps

**Comment by samlane-ma** [comment]
As of right now, it appears due to Minecraft changes that there is no "out-of-the-box" way to run the Minecraft Java version.  It is necessary to compile a compatible version of MultiMC, or rely on 3rd party apps or or scripts to do so. I tested out these methods however, with success.  By reducing the graphics settings to Fast, turning off the smooth lighting, reducing the render distance, and playing in full screen mode at 1024x786 I was able to achieve around 5-14 FPS at these settings (pi 4 4gb model, not overclocked) with occasional drop below, on average around 8-10.

Unfortunately, without an official Java version is capable of working on the Pi, and given the specs of the Pi, I don't think we can expect any more out of it than this.
